# Generated by Django 4.2.8 on 2023-12-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20231226_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='phone',
        ),
        migrations.AddField(
            model_name='country',
            name='phone_code',
            field=models.CharField(default='+91', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='state',
            name='phone_code',
            field=models.CharField(default='+91', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='avg_age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='city',
            name='num_of_adult_females',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='city',
            name='num_of_adult_males',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='city',
            name='population',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_code',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='gst_code',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'city_code', 'state')},
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together={('name', 'country')},
        ),
    ]
